### ISSUE TITLE
High CPU Load when secret key is not available (e.g. YubiKey not inserted)

### ISSUE THREAD

**Issue by leona-ya** [plattfot/pinentry-rofi#4] opened 2020-04-30 16:18 UTC
I use pinentry-rofi with my GPG-Key saved on my YubiKey (as smartcard). When I try to use GPG without having the YubiKey inserted, pinentry-rofi does not show an error message an creates a high CPU load and temperature. After inserting the YubiKey the load falls and the message for entering the password shows up

**Comment by plattfot** [comment] 2020-04-30 18:25
Not sure if this the fault of pinentry-rofi, as it only sets up the interface for typing in the password. It should just wait for input and not waste cpu cycles spinning in some loop. Or abort if it gets a command it doesn't understand. I could be wrong though.

I only have a yubikey standard which I bought in 2013 so cannot really reproduce this. What is the behavior of other pinentry programs? Do they error out?

**Comment by n0emis** [comment] 2020-05-01 14:45
I can reproduce this. It seems like `pinentry-rofi` crashes and get's respawned by gpg-agent, because it changed its PID in a matter of seconds. I had to kill my gpg-agent to stop this.

**Comment by plattfot** [comment] 2020-05-01 23:30
Ok, cool. Then that explains the high CPU load.

I changed the behavior when it encounter an unknown command. Instead of bailing out, it now print an error message with the gpg error code for not implemented.

I  also fixed an issue with it not exiting when the command `BYE` is given.

And lastly I added an option `--log <logfile>`, where `<logfile>` is a path to a file. It will then write out unknown commands it encounters to it, which hopefully can help debug stuff like this. It will append the PID to the filename.
If you have added `pinentry-rofi-guile` to /usr/bin/pinentry, usage would be
``` sh
#!/bin/sh

exec /usr/bin/pinentry-rofi-guile --log /tmp/pinentry-rofi "$@"
```

All this are added to the `high_cpu_load_4` branch. Please test it out and see if it fixes the issue. And if not please attach the log of one run. That would help me tremendously to track down the issue. Just make sure no sensitive information is included in the log.

Thanks

**Comment by n0emis** [comment] 2020-05-02 00:03
The following message seemed to appear a lot in the logs: 
```
Unknown command: "CONFIRM"
```

**Comment by plattfot** [comment] 2020-05-02 02:27
Ok, it's probably trying to pop up a window of some sort. My guess is notify the user that it cannot find the key and either continue or cancel. Need to check the source code for some other pinentry implementation and see if I can figure it out. Should be doable to pop up a rofi window with the message.

**Comment by plattfot** [comment] 2020-05-02 06:02
Added a pop up when the `CONFIRM` command is used, please test it out as I have no way of reproducing this.

Thanks

**Comment by n0emis** [comment] 2020-05-02 12:06
Thanks, that already works well. (With some minor displaying issues, see the attached screenshot)
![Screenshot from 2020-05-02 13-57-52](https://user-images.githubusercontent.com/22817873/80863514-4551a280-8c7d-11ea-9adc-db0977518d7e.png)
~@n0emis @em0lar

**Comment by n0emis** [comment] 2020-05-02 12:13
Is this also the `CONFIRM` pop-up? Because it has the same issue with linebreaks...
![Screenshot from 2020-05-02 14-08-04](https://user-images.githubusercontent.com/22817873/80863811-f0af2700-8c7e-11ea-9be8-521e6466bea7.png)

**Comment by plattfot** [comment] 2020-05-02 21:05
Glad to hear it works. Yeah both are the `CONFIRM` pop up. I'll look into why the linebreaks isn't working. And also fix the prompt, it shouldn't say `Passphrase::`

**Comment by plattfot** [comment] 2020-05-03 19:05
Try it now, it should properly handle newlines in the description.

**Comment by n0emis** [comment] 2020-05-03 23:51
Hmm, unfortunately not for me. I can still see `\n` but no newlines in the output.

**Comment by plattfot** [comment] 2020-05-03 23:58
Ok, strange. Can you run the script manually and type in after the prompt `OK Please go ahead`
```
SETDESC Foo\nBar
CONFIRM
```
Do you see a newline in the pop up? Or is it `Foo\nBar`?

You can exit the script with either `ctrl+c` or type `BYE`.

**Comment by leona-ya** [comment] 2020-05-04 10:43
It's really strange. When I do it manually it works (it has a new line and no \n in it)

**Comment by n0emis** [comment] 2020-05-04 11:04
I have a solution: instead of replacing `"\\\\n"` you have to search for `"%0A"`. Then it works.

The pinentry docs (for example at http://info2html.sourceforge.net/cgi-bin/info2html-demo/info2html?(pinentry)Protocol) states the following:
> Note that all strings are expected to be encoded as UTF-8; PINENTRY takes care of converting it to the locally used codeset. To include linefeeds or other special characters, you may percent-escape them (e.g., a line feed is encoded as %0A, the percent sign itself is encoded as %25, etc.).

**Comment by plattfot** [comment] 2020-05-04 18:45
Thanks @n0emis, changed the `\\\\n` to `%0A` hopefully that works.

And thanks for finding the manual protocol, found some other things `pinentry-rofi` isn't supporting. For example handling underline, better default handling of the ok and cancel button and handling `CONFIRM --one-button`/ `MESSAGE`. But they're out of the scope of this issue so I haven't pushed them to the `high_cpu_load_4` branch.

**Comment by n0emis** [comment] 2020-05-04 19:15
Thanks for looking into this. That has fixed our problems...

**Comment by plattfot** [comment] 2020-05-04 19:18
Perfect, then I'll close this issue and merge the branch to master. Please reopen if that's not the case.

**Closed as completed by plattfot** 2020-05-04 19:18 UTC
Labels: bug
